In [1]:
import pandas as pd

# importing data
train_data_clean = pd.read_csv('/content/train_data_clean.csv')
train_data_clean.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50

In [28]:
# Select operation
#selecting the specific columns
selected_data = train_data_clean[['Name', 'Location', 'Year', 'Kilometers_Driven', 'Owner_Type', 'Mileage',
                  'Engine', 'Power', 'Seats', 'Price']]
selected_data.head()

,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
1,Honda Jazz V,Chennai,2011,46000,First,13 km/kg,1199 CC,88.7 bhp,5.0,4.50
2,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
4,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,3.50

In [15]:
#Filter operation
#filtering dataset with location 'Chennai' and fuel_type 'Petrol'
filtered_data = train_data_clean[(train_data_clean["Location"] == "Chennai") & (train_data_clean["Fuel_Type"] == "Petrol")]
filtered_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
52,Hyundai Grand i10 Sportz,Chennai,2015,54000,Petrol,Manual,Third,18.9 kmpl,1197 CC,82 bhp,5.0,4.78 Lakh,3.60
74,Toyota Innova 2.0 G1,Chennai,2006,230000,Petrol,Manual,Third,12.4 kmpl,1998 CC,132 bhp,8.0,4.78 Lakh,4.50
129,Maruti Alto LXi BSIII,Chennai,2010,94385,Petrol,Manual,Second,19.7 kmpl,796 CC,46.3 bhp,5.0,4.78 Lakh,1.60
214,Maruti Wagon R LXI,Chennai,2004,61000,Petrol,Manual,Second,18.9 kmpl,998 CC,67.1 bhp,5.0,4.78 Lakh,1.25

In [29]:
# Rename operation
#Renaming columns Mileage, Engine, Power with Mileage(kmpl), Engine(CC), Power(bhp)
renamed_columns = train_data_clean.rename(columns={"Mileage": "Mileage(kmpl)", "Engine": "Engine(CC)", "Power": "Power(bhp)"})
renamed_columns.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage(kmpl),Engine(CC),Power(bhp),Seats,New_Price,Price,Age,Kilometers_Per_Year
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50,9,4555.555556
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,13,3538.461538
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00,12,7250.000000
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74,11,3697.272727
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50,11,7909.000000

In [21]:
# Mutate operation (
# Adding new columns "Age" and "Kilometers_Per_Year"
current_year = 2024
train_data_clean['Age'] = current_year - train_data_clean['Year']
train_data_clean['Kilometers_Per_Year'] = train_data_clean['Kilometers_Driven'] / train_data_clean['Age']
train_data_clean.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age,Kilometers_Per_Year
0,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50,9,4555.555556
1,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,13,3538.461538
2,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00,12,7250.000000
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74,11,3697.272727
4,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50,11,7909.000000

In [30]:
# Arrange operation
# Arranging or sorting data based on kilometers_driven
arranged_data = train_data_clean.sort_values(by="Kilometers_Driven")
arranged_data.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age,Kilometers_Per_Year
1315,Maruti Alto 800 2016-2019 VXI,Mumbai,2019,171,Petrol,Manual,First,24.7 kmpl,796 CC,47.3 bhp,5.0,4.78 Lakh,3.60,5,34.200000
5451,Maruti Wagon R ZXI AMT 1.2,Mumbai,2019,600,Petrol,Automatic,First,21.5 kmpl,1197 CC,81.80 bhp,5.0,6.8 Lakh,6.25,5,120.000000
1203,Jaguar XE 2.0L Diesel Prestige,Delhi,2018,1000,Diesel,Automatic,First,13.6 kmpl,1999 CC,177 bhp,5.0,52.77 Lakh,40.00,6,166.666667
165,Hyundai Grand i10 1.2 Kappa Asta,Kolkata,2019,1000,Petrol,Manual,First,18.9 kmpl,1197 CC,81.86 bhp,5.0,7.39 Lakh,6.50,5,200.000000
1123,Tata Tigor 1.2 Revotron XTA,Ahmedabad,2018,1000,Petrol,Automatic,First,20.3 kmpl,1199 CC,84 bhp,5.0,4.78 Lakh,6.85,6,166.666667

In [31]:
# Group By operation
# Sum of Kilometers_Driven and Mean price for each location
summary_data = train_data_clean.groupby("Location").agg({"Kilometers_Driven": "sum","Price": "mean"})
summary_data.head()

            Kilometers_Driven      Price
Location
Ahmedabad            11984485   8.567248
Bangalore            20496207  13.482670
Chennai              43075555   7.958340
Coimbatore           29625311  15.160206
Delhi                30880339   9.881944